# Generated by Django 4.0.6 on 2022-07-15 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSecond', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='precio_platillo',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Precio del Platillo'),
        ),
    ]
