# Generated by Django 4.0.6 on 2022-07-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSecond', '0002_alter_platillo_precio_platillo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='id_pedido',
            field=models.ManyToManyField(to='appSecond.pedido'),
        ),
    ]
